### PR TITLE
add JS configuration

### PR DESCRIPTION
**Pull request by jbw**
Adds:
* code linter and rules
* slight restructure given config additions
* editor standard config
* scripts to run tests and generate parser.js
* add yarn and npm lock file

### CODE REVIEW

**Comment by ocharles** [comment]
Cool, this looks great! I don't think I want to commit the generated parser though, can you remove that?

**Comment by jbw** [comment]
@ocharles i'll probably fix up the code post linting since i forgot to do that then it should be good to merge.

**Comment by ocharles** [comment]
Rad. Give me a ping when you're happy.

**Comment by ocharles** [comment]
I have a bunch of changes to the normalizer.js, but unfortunately I left them at work. So if you wanted to work on that, that would have to wait until tomorrow. Happy to take linting changes or anything other small code that is a better form of what this currently is. Hold off on any huge refactorings though (`normalize.js` is intentionally terrible at the moment) as I just want to sketch the landscape out first.

**Comment by jbw** [comment]
@ocharles cool no worries. I've started with the tests so I'll leave normaliser.js. You can pull in the configs run the linting script (npm lint) to see what it complains about!

**Comment by jbw** [comment]
@ocharles good to go now. ignore the normalise.js changes i didn't change anything apart from running the linter over it with --fix.

**Comment by ocharles** [comment]
Awesome, thanks! Any thoughts on Prettier?

**Pull request merged**
