### PR TITLE
Change shift function Number.Integer check

### PR DESCRIPTION
**Pull request by jbw**

### CODE REVIEW

**Comment by ocharles** [comment]
Did you mean to remove BigNumber from package.json?

**Comment by jbw** [comment]
@ocharles it's in there.  (https://github.com/jbw/dhall.js/blob/de33c9a2ed72d2192ab6bea7a294e1b2da84b8cf/package.json)

It wasn't originally so i added it but it was the wrong bignumber package so i removed and added the correct one.

**Comment by ocharles** [comment]
Ah, I see, it left `devDependencies` which sounds right.

**Comment by jbw** [comment]
@ocharles any thoughts on the code above? Why are we erroring if a Var isn't numeric? Should we be doing this or was it debug code left over?

**Comment by ocharles** [comment]
Because JavaScript doesn't have a type system. The input to car must be
numeric so I'd rather just guard it. I'm away at the mo, so it'll be a
while until I get to this one.

**Comment by jbw** [comment]
Makes sense if it is **always** numeric but from the looks of it Var can be an expression too ('1-1') so maybe something has to done or checked here too.

**Comment by ocharles** [comment]
No, it should always be a number. 1-1 should be 0.

**Pull request merged**
